### ISSUE TITLE
[DeluxeMenus] Add new Requirement types to wiki

### ISSUE THREAD

**Issue by Andre601** [HelpChat/Wiki2#7]
DeluxeMenus now has new requirement options available to use, which are namely:
- `!has item`
- `!has money`
- `!has permission`
- `!string contains`
- `!string equals`
- `!string equals ignorecase`
- `!regex matches`

Considering that only differentiate from the others by being prefixed with an exclamation mark, would I suggest to just mention, that you can invert the methods by prefixing it with a said exclamation mark.

**Comment by aBooDyy** [comment]
Added.
Thank you.
